### ISSUE TITLE
Atlas Navbar Suggestion - Replace navbar items on smaller resolutions with a pull down menu button

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#319]
Would it be possible for Nunaliit (by default) replace it's navbar with a menu button on smaller screen resolutions? An example of this is seen with many bootstrap style/mobile friendly webpages. 

This would address the issue of crowding menu items on smaller screens.

**Comment by ahayes** [comment]
It is possible. All HTML and CSS is customizable by atlas builders. You can opt not to use the optional navigation menu compiler and roll your own. We don't currently have plans to develop an alternate small screen friendly "demo" template but would welcome any pull requests that take us in that direction. We are instead working on a Nunaliit app that would focus on data acquisition/editing rather than rendering map modules.
