### ISSUE TITLE
Can cluster symbology be added to an atlas's legend?

### ISSUE THREAD

**Issue by afitzgerrell** [GCRC/nunaliit#373]
ICC would like me to add the cluster symbology to the ArcticCBM legend, is this possible?
Thanks, 
Amy

**Comment by jpfiset** [comment]
Is it possible? Yes, with a lot of work. Nunaliit currently does not support adding the clusters in the legend, since the legend is a layer selector (which doubles as a legend).

However, it would be possible to augment the layer selector with custom information. The element that contains the layer selector can be selected with $("div.layersDiv"). Probably the best place to insert the code would be in the nunaliit_custom.js. One could register for the event 'reportModuleDisplay', look for the element and augment it with more legend information.

**Comment by ahayes** [comment]
Amy, some custom code could do the trick as JP suggests. But you could also have the cluster symbology share the same colour/fill/shape as the layer and do something more subtle for the cluster like increase the radius, thicken the stroke, and include a label inside with the number. That way it can still be recognized as the same type of symbol as far as the layer selector/legend goes.

**Comment by afitzgerrell** [comment]
Hi Amos and JP - thanks for your responses.  I'll note the options you provided and let the powers that be work out the most appropriate solution.  I'm no longer on this project as I've taken on a new position at NSIDC.  I appreciate the help you've provided over the past year or so, and I've quite enjoyed working with Nunaliit!

Kind regards,
Amy
