### ISSUE TITLE
Unable to recover password

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#393]
When attempting to go reset a password via the 'I forgot my password' process, it is possible to receive the following error:

"Unable to recover password: error"

The user seems valid and I'm not sure what is causing the problem.

**Comment by jpfiset** [comment]
From my testing, the usual password recovery seems to work fine. That is, a user created via mail registration can recover the password, successfully.

However, if a user was created directly (using the user page, by-passing the e-mail registration), I observe a failure during the password recovery.  The underlying issue is that there is no verified e-mail address associated with this user.

Although the server is reporting the source of the error to the client, this information is not presented to the user. I have just updated master (commit above) to improve error reporting.

**Comment by jpfiset** [comment]
Can you please provide me with information as to which atlas and which user is failing?

**Comment by jpfiset** [comment]
On the Thule atlas, the following error is returned by the server: {error: "Password recovery URL is not provided"}

The first problem is that the client is not passing this information to the user. The changes committed above should deal with this.

The second problem is that the server should not report that user registration is available unless the recovery URL can be computed. Looking into this.
