### ISSUE TITLE
Bug: br element required with multiple fields of type localized in schema form view

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#498]
**Bug:** When a schema is defined as having an attribute of type localized, the first set of span and textarea elements are vertically aligned correctly, however subsequent textareas are offset. 

**Suggestion:** Maybe a br element is needed after the span?

![missalignedtextarea](https://cloud.githubusercontent.com/assets/6431161/15402499/7a59a4ba-1dc2-11e6-93f7-6c60580513e7.png)

**Comment by jpfiset** [comment]
This is the HTML generated from a localized textarea:

````html
<div class="demo_test_description">
		<div class="label n2s_localized">Description</div>
		<div class="value">
            <div class="n2schema_field_wrapper">
                <div class="n2schema_field_container n2schema_field_container_localized">
                    <span class="n2_localize_lang">(en)</span>
                    <textarea placeholder="Description" class="n2schema_input n2schema_selectorsdemo_137test-sdescription-sen n2schema_type_localized"></textarea>
                </div>
                <div class="n2schema_field_container n2schema_field_container_localized">
                    <span class="n2_localize_lang">(fr)</span>
                    <textarea placeholder="Description" class="n2schema_input n2schema_selectorsdemo_137test-sdescription-sfr n2schema_type_localized"></textarea>
                </div>
            </div>
        </div>
    </div>
</div>

````

I do not see what you are mentioning. However, I suspect that you have a font where "(fr)" is slightly narrower than "(en)" and that it fits left of the textarea.

Introducing a "br" element would not help, in this case. This is a CSS issue.

If you look at line 36 of the file nunaliit2/nunaliit2-js/src/main/js/nunaliit2/css/basic/n2.displayLayoutFloat.css:

````css
.n2_documentForm .n2_layoutFloat textarea {
	width:90%;
	height:200px;
}
````

The width is set at 90%. I suspect that it was not set at 100% because of the padding.

Play with that value to see if it fixes your problem.

**Comment by jpfiset** [comment]
Maybe you should try:

````css
.n2_documentForm .n2_layoutFloat textarea {
    width: 100%;
    height: 200px;
    margin: 0;
    padding: 0;
}
````

**Comment by boikle** [comment]
Increasing the width to 100% solved the problem. Thanks JP.
