### ISSUE TITLE
Error during video upload

### ISSUE THREAD

**Issue by cmcneave** [GCRC/nunaliit#569]
While uploading video files in Nunaliit 2.2.4, the progress hangs with an error in the log reading: 

2016-10-03 13:22:53,353[ERROR]: Unable to create an upload request
ca.carleton.gcrc.couch.client.impl.CouchDbException: CouchDB Error (403) forbidden/Database submissions are restricted to users that have accepted the user agreement

However, in docs/org.nunaliit.user_agreement/nunaliit_user_agreement/enabled.json is set to "false" so the behavior is unexpected.

**Comment by jpfiset** [comment]
This is a bug in 2.2.4 that was fixed in 2.2.6.

The work around for this issue, in 2.2.4, would be to turn off restriction on users, as explained here:

https://github.com/GCRC/nunaliit/wiki/Atlas-Builder-Documentation#locked-down-atlas

Instead of turning on the restriction, turning it off would be to assign "false".

Another approach would be to upgrade your atlas to 2.2.6 or a newer version. We just released 2.2.7 and are working at stabilizing 2.2.8.
