### ISSUE TITLE
Media recording directly in browser

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#629]
Would like to be able to have Nunaliit users record audio/video directly in the browser as an optional alternative to choosing a file for upload.

This site documents a bunch of libraries and demos of recording media in the browser using WebRTC/MediaRecorder APIs. 

https://www.webrtc-experiment.com/

**Comment by ahayes** [comment]
This is an interesting example of streaming the audio to the server as it is recording. It may be better than trying to capture the whole thing on the client and sending it in a big blob while the user waits afterwards.

**Comment by boikle** [comment]
Interesting problem. The WebRTC site offers a great example of this tech at https://www.webrtc-experiment.com/RecordRTC/ . I like this example because it allows the user to define the type of recording session (audio, audio+video, etc) as well as defining which hardware to use for recording, and prompting the user for permission to access the hardware. I also like the idea of either saving the file to disk or directly to the atlas db. 

Since I suspect this tech will likely be a modification of the existing upload file option we use for our schema docs. Should we create a new option for schemas that creates an audio recording button which opens a ui window with the options described above? Or is this approach too narrow in scope and should be extended to be a new atlas tool page which allows users to record new media content which can be attached to existing docs, after the fact?

**Comment by ahayes** [comment]
I think we need a new "File" widget that allows for selecting or drag&dropping a file or recording a new file (audio only or video with audio) directly in the browser.

For audio only recordings, PCM/WAV data created by the browser should be compressed to MP3 on the client side before sending.  This library seems to be the best available code for that: https://github.com/zhuker/lamejs
