### ISSUE TITLE
Find on Map button missing for maps based on models

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#642]
Find on Map buttons are marked as not available when using models to generate the collections of features to display, even when those features have geometries and are visible on the map.

Of relevance seems to be that the findIsAvailable message to the dispatcher is commented out in n2.couchDbPerspective.js for both DbPerspective and ModelCouchDbView classes.

**Comment by boikle** [comment]
I can't reproduce this bug. Is this still an issue?

**Comment by boikle** [comment]
I was able to reproduce this bug today, and was able to track down what causes it. 

**Why the bug is occurring:**
When the 'n2show_findAvailable/n2show_findNotAvailable' show service is invoked on a document, it checks with the dispatcher if 'find is available' for the document. This check consists of two parts. 1) does the document have a geom, and 2) does the document belong to a layer which is used by the map's overlay. 

When a map only uses a model (i.e the overlays in the map.json are referencing a model id), the dispatcher uses that model id when performing the layer check. So if the document doesn't have a layer which matches this model id, the 'find is available' check returns false, and the 'Find on Map' button doesn't appear in document display. 

**Example:**
I have model called 'documentModel' which uses a layer selector for all documents on the 'nunaliit' layer. When I display one of these documents, the dispatcher checks to see if the find is available, and is shown that my document is only associated with the 'nunaliit' layer and not with the 'documentModel' layer. At which point the dispatcher notifies the show service that the find is not available, and consequently the find on map button is not displayed.

**Comment by boikle** [comment]
@ahayes How would you like to handle this?

**Comment by ahayes** [comment]
This warrants a design conversation. If we can't find the correct model automatically, then perhaps the find on map functionality needs to become a utility with some configuration so that we can point it at the model that the map is using? Are there other canvases that we would want to find a document on?

**Comment by ahayes** [comment]
I set up an atlas this week. It uses a map with an overlay of type "model". The sourceModelID is "augment" and that is not a layer id in any of the documents being rendered.

The Find on map button appears and works as expected when the doc is displayed in the side panel and when it is listed in a search result. So we might need to dig a bit more to reproduce and/or confirm that it is no longer an issue.
