### ISSUE TITLE
Build build date and revision to Nunaliit version command

### ISSUE THREAD

**Issue by jpfiset** [GCRC/nunaliit#695]
Collect date and revision at build time. Display in command 'nunaliit version' and in configuration welcome.

This is to help identifying builds and deployments.

**Comment by jpfiset** [comment]
Added logic to detect discrepancies between server and Javascript code by comparing build numbers.

**Comment by jpfiset** [comment]
Change the final name of the SDK artifact to represent the short build number.

**Comment by boikle** [comment]
I'm not sure if this an issue or not, but I wanted to bring it up, just in case. With the new date and time strings added to the file name (e.g. nunaliit_2.2.9-SNAPSHOT_2017-10-31 18:03:56 -0400_f65f80c.tar.gz). I noticed I needed to add a --force-local option to be able to extract the file or I needed to rename the file to remove the colon from the file name. 

Note: This issue also exists in the extracted contents. A nested directory with the same name as the tarball is inside.

Obviously performing either task is not a problem, but it does add extra work on the part of the atlas builder, or needs a user to figure out why they can't extract the tarball in a more common way. Would it be possible to use a different representation of time instead of the date and time strings? Perhaps an epoch timestamp number or just the date string?

**Comment by ahayes** [comment]
The datestamp and shortened build code is supposed to be in the file name. The timestamp isn't. I think this was just a booboo on JP's part.

**Comment by ahayes** [comment]
Actually... Maybe there is something different in your build environment than JPs? Looking at his code, I don't see where the "time" part goes in. It looks like YYY-MM-DD date and shortbuild should be it.

**Comment by boikle** [comment]
Talked with Amos about this issue, and he suggested I update the build.date name used in the utils pom.xml a different name than what is used in couch sdk pom.xml. So I changed it to build.date.time, and this is solving this issue on my machine. Note sure if this is a fix or not (could just be something wrong with my build environment) but I will make a pull request in a moment for you to consider.

**Comment by jpfiset** [comment]
Yes, building the project nunaliit2-couch-sdk by itself was yielding the proper names. Building all of nunaliit2 was creating an unworkable name scheme. The issue is that the property names in Maven are global.

I have prefixed the property names with n2.xxx. so that they do not clash with other projects.
