### ISSUE TITLE
Layer assignment is different based on document creation method

### ISSUE THREAD

**Issue by boikle** [GCRC/nunaliit#700]
It was pointed out to me recently that this remains an issue when making documents in a different ways.

**Observed Behaviour:**

* If you create a document via the create document widget, the inital layer(s) which are set in the definition.json file, are the layer(s) is being stored in the new document.
* However if you create a document with the add or edit a map feature button, only the public layer is applied and the initial layer(s) appear to be ignored.

**Comment by ahayes** [comment]
This is not ideal, but I think I know how we arrived at this outcome. Features being added to the map by someone who isn't logged in (depending on auth config) or doesn't otherwise have privileges need to be added to public to be accepted. There is a conversation needed about this and Issue #442 as well.

**Comment by jpfiset** [comment]
At the time this logic was developed, Nunaliit did not have utilities. Since utilities have been developed, it is possible to specify "assignLayerOnDocumentCreation" on a module.

The idea of assigning layers based on schema was good at a time when we could only filter a map based on layers. However, this approach is starting to feel dated.

The feature where any map feature should be added to the public layer also seems outdated. This should be specified on a per-module basis.

**Comment by jpfiset** [comment]
Removed hard coded assignment of layer "public" from document editor. Added ability to specify a layer id only for documents with geometries, in utility "assignLayerOnDocumentCreation"
