### ISSUE TITLE
tarball filename and extracted directory name change

### ISSUE THREAD

**Issue by billingb** [GCRC/nunaliit#714]
I just generated a SNAPSHOT tarball and extracted it using the most up to date Nunaliit source. The old tarball's had a pattern nunaliit2-couch-sdk-<version> for the tarball and the extracted dir. The new 2.2.9 SNAPSHOT has pattern nunaliit_<version> for both. I'm updating automation to work with the new pattern and want to confirm that this is a change to the naming convention not just for the SNAPSHOT but for future versions of the software that will be released.

Thanks!

**Comment by ahayes** [comment]
Due to some people (who shall remain nameless) having a series of issues related to version mismatches, we did quite a bit of work to embed and check version & build numbers in server and client code. We extended this to the tarball file naming conventions and took the opportunity to adjust those a bit too.

I think we will stick with the current scheme for the foreseeable future. There is some tension between timeliness of releases, stability of releases, and simply being able to see what is newer/older based on a version number (that a build's git hash doesn't provide.) I think this is the best we can do for the moment.

Note that if you are adjusting your deployment environment, you should also switch from init.d scripts to systemd scripts if you haven't already. Take care to make sure the correct one is invoked.
