### ISSUE TITLE
Video capture in browser results in playback problems

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#719]
When recording video into Nunaliit via the browser (Chrome 64.0.3282.167 on OSX) everything seems OK during recording and preview. Upload succeeds. When reviewing the file in the Upload Approval page, the original is fine. The converted file is very pixelated and the audio is poor. In addition, after approval, playback may result in the attached error (see screenshot).

This problem seems to be intermittent but I have seen this several times now and have a system where I have only ever seen it fail so hopefully we can reproduce.

<img width="1623" alt="screen shot 2018-02-16 at 17 28 53" src="https://user-images.githubusercontent.com/1750076/36336708-1107fae2-133f-11e8-835f-a5c1c0bb1695.png">

**Comment by ahayes** [comment]
I found this info about the error message shown in the screenshot.
https://stackoverflow.com/questions/37674223/domexception-failed-to-load-because-no-supported-source-was-found

**Comment by jpfiset** [comment]
I am not able to reproduce this problem. Can you point to an atlas and a video?

**Comment by jpfiset** [comment]
There were two issues here:
1. The wrong codec for AAC was loaded on the server. This caused the conversion to fail.
2. In some circumstances, Chrome sends a WEBM h.264 with a profile of "baseline", instead of "constrained baseline". When the file with baseline profile is encountered by the converter, the converted file ends up with 1000 fps. We were able to fix this issue by adding "-r 24" to the conversion line, forcing the frame per seconds (fps) to 24.

Forcing the output fps might be a feature we want to add to all conversions.
