### ISSUE TITLE
Tabular data import and display

### ISSUE THREAD

**Issue by billingb** [GCRC/nunaliit#729]
It is my understanding that Nunaliit has new functionality to support loading and displaying large amounts of tabular data. However, I've been unable to locate any documentation to understand this functionality. It's entirely possible I've just overlooked it, hoping you can point me in the right direction to get started.

Thanks,
  Brendan

**Comment by billingb** [comment]
Related question. After getting the tabular display working using a module with a canvas the user now wants to know if I can display the tabular data when selecting a document (on the map) in the sidebar. In short the desired functionality would be:
user clicks on station in map (selecting the station document for display)
Station display triggers display of table data (and in future graph) for the data related to the select station either in side panel or in additional portion of the screen.

I think this would require displaying two modules at the same time, and from my limited knowledge this wouldn't be possible. I looked through the widgets thinking this is where I would find something if it existed but don't see anything. So can you either point me in the right direction or let me know if this is not possible?

Thanks!

**Comment by billingb** [comment]
I figured out a solution to this for a small amount of data, having the user put CSV into a text field and then using javascript to display the csv as a graph and/or table.

**Comment by boikle** [comment]
Hi Brendan,

Thank you for pointing out the gaps in our wiki. Following our converstations through email, I’ve since added documentation on both the [Table Canvas](https://github.com/GCRC/nunaliit/wiki/Nunaliit-Documentation-for-Atlas-Builders#atlas_canvas_table) and the [ElementGenerator](https://github.com/GCRC/nunaliit/wiki/Nunaliit-Documentation-for-Atlas-Builders#atlas_elementgenerator), which I think answers your original question. 

Bob
