### ISSUE TITLE
Provide audio and video requirements in multimedia.properties

### ISSUE THREAD

**Issue by sruest** [GCRC/nunaliit#906]
Allow atlas builders to configure required audio and video settings in the `multimedia.properties` file.  Specific settings are documented in `multimedia.properties` and  https://github.com/GCRC/nunaliit/wiki/Nunaliit-Documentation-for-Atlas-Builders#configuration_multimedia

**Comment by ahayes** [comment]
The solution looks good and I appreciate the ability to specify multiple evaluation criteria (although there might be some confusion with the property being singular. What happens if someone repeats the identical property several times? We might be able to clear this up with some wording changes. I can help with this.

Also, the intro paragraph in the new documentation for this suggests that you can configure "requirements" (plural) that need to be met to avoid processing. Can you please clarify in the docs how the multiple thresholds are processed? Are they evaluated in order with any match skipping the rest of the threshold tests and skipping the encoding? Or do they all have to be met? Are the thresholds evaluated per upload type (audio/video/photo)? What about "other" types?

I think it would be helpful to revisit if/when to use "requirement" in place of "threshold" as the feature is explained. I think threshold is the more correct term as it represents a line crossed rather than a fixed set of properties.

**Comment by sruest** [comment]
I updated the docs to try and make them more clear.  Thresholds separated by a "|" are evaluated with "OR" - only one needs to pass to allow a file to upload without conversion.  The conditions within a threshold (separated by ",") are "AND" evaluated, so they all need to pass for the overall threshold to pass.

Please have a look at the docs and feel free to improve them.  Thanks Amos!

**Comment by ahayes** [comment]
Thanks, Sarah. I will have a look later. GitHub has been having intermittent trouble rendering the atlas builder doc page because it is too long so I will try to break it up a bit too while I am at it.

**Comment by ahayes** [comment]
[Multimedia section](https://github.com/GCRC/nunaliit/wiki/Nunaliit-Documentation-for-Atlas-Builders#configuration_multimedia) of the wiki updated.
