### ISSUE TITLE
Mr Alexander Appleton

### ISSUE THREAD

**Issue by Waterloo15** [GCRC/nunaliit#946]
Hi there
I am a history PHD student who is interested in using this software to build a historical map of the merchant connections in Manchester England during the mid Nineteenth Century. I am a bit confused on how I actually get started. Do I need a disk to download this software and does it cost anything? Is there anything I need to install onto my computer beforehand? Will a normal laptop with Microsoft Windows be good enough to do the job? Thank You

**Comment by rmjatlas** [comment]
Good afternoon Mr. Alexander Appleton,

Please see the [Nunaliit documentation page](http://nunaliit.org) for information about how to get started as an atlas builder (i.e., see the latest pre-built binary and documentation wiki). The Nunaliit Cybercartographic Atlas Framework is open-source licensed [The 3-Clause BSD License](https://raw.githubusercontent.com/GCRC/nunaliit/master/license.txt), meaning there is no explicit cost to access, however, any use of the software must respect the license agreement. As for your query about building an atlas on a standard laptop with Microsoft Windows, it is probably best to run your computer specifications by the GCRC lab coordinator, Amos Hayes. The GCRC is not accessible at this time due to covid-19 restrictions.

I hope this is helpful in answering your query this afternoon.
-Ryan

**Comment by ahayes** [comment]
Hi @Waterloo15 . Apologies for my delay in responding to you. If you are starting from absolute scratch, I will say that Nunaliit is a server-side application for building "atlas" websites. If you are not familiar with linux or other unix-like operating systems then you may find the learning curve a bit steep to get up and running, but it does not require you to be a web developer to build an atlas so while it might be challenging, it is perhaps easier than writing all the code from scratch.

The nunaliit github wiki link above will take you to the docs. There is a relatively new "Nunaliit Tutorial" project wiki linked from there too. It was written by a former Nunaliit developer to assist new users who may not know about virtual machines, unix, etc. That is probably the best place for you to start. It walks you through how to set up a linux virtual machine, install nunaliit, and get a basic atlas up and running for you to customize. Then you can move beyond the tutorial using the Atlas Builder documentation to see all the various options for configuring Nunaliit to organize your specific data.
