### ISSUE TITLE
Import with UTF8 characters sometimes breaks

### ISSUE THREAD

**Issue by billingb** [GCRC/nunaliit#948]
When importing data that contains UTF8 characters sometimes the encoding of the data does not properly handle the UTF8 characters and the import fails.

**Comment by NassefAsh** [comment]
The n2.base64 encode and decode functions do not differentiate between character byte sizes, and treat all characters as 1-byte characters. This is the source of the issue, it fails with 2-byte, 3-byte, and 4-byte characters. The current stop-gap measure is to use a UTF-8 encoder ([Click here for UTF-8 code source](https://github.com/mathiasbynens/mothereff.in/blob/9cd5ec4649db25ae675aec25f428f3ddf3d9a087/utf-8/vendor/utf8.js#L69)) wrapped around the n2.base64 encode and decode functions. Since the UTF-8 code does differentiate between character byte sizes, it is used as follows:

Encode:
1 - Encode imported data using UTF-8 encoder.
2 - Pass the UTF-8 encoded data to the base64 encoder.

Decode:
1 - Decode data using base64 decoder.
2 - Decode base64 decoded data using UTF-8 decoder.


The proposed solution is to write code in the base64 encode and decode functions to differentiate between byte sizes.


*For reference, an explanation of UTF-8 character byte sizes*
1 byte for standard English letters and symbols.
2 bytes for additional Latin and Middle Eastern characters.
3 bytes for Asian characters.
4 bytes for all additional characters.
([Source](https://techterms.com/definition/utf))

*Additional info for proposed solution*
Found in [this Stack Overflow answer by Jonathan Leffler](https://stackoverflow.com/questions/1319022/really-good-bad-utf-8-example-test-data):

In UTF-8, you get the following types of bytes:

Binary...........Hex.....................Comments
0xxxxxxx......0x00..0x7F........Only byte of a 1-byte character encoding
10xxxxxx......0x80..0xBF........Continuation bytes (1-3 continuation bytes)
110xxxxx......0xC0..0xDF.......First byte of a 2-byte character encoding
1110xxxx......0xE0..0xEF........First byte of a 3-byte character encoding
11110xxx......0xF0..0xF4........First byte of a 4-byte character encoding
